# The formatter set, imported by devenv.nix so the shell, the git hook and CI
# all read one definition.
{
  projectRootFile = "Cargo.toml";

  programs = {
    # Nix.
    alejandra.enable = true;

    # Rust. The edition must match [workspace.package] in Cargo.toml: rustfmt
    # sorts `use` items differently per edition, so a mismatch makes treefmt and
    # `cargo fmt` fight over every file.
    rustfmt = {
      enable = true;
      edition = "2024";
    };
  };

  settings.global.excludes = [
    # Generated by crate2nix, rewritten by the cargoNixSync hook. Formatting it
    # makes the two fight: treefmt reformats, the hook regenerates, and no
    # commit ever settles.
    "Cargo.nix"
    "target/*"
    "analysis/*"
    "*.wav"
  ];
}
